name: Docker Image CI

on:
  push:
    branches: [ "project" ]
  pull_request:
    branches: [ "project" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: chekout code
      uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build -t new:latest .
